version: '3'
x-spark-common: &spark-common
  image: bitnami/spark:3.5
  volumes:
      - ./jobs:/opt/bitnami/spark/jobs
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        image: apache/airflow
        command: scheduler
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./jobs:/opt/airflow/jobs
    webserver:
        image: apache/airflow
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./jobs:/opt/airflow/jobs
        ports:
            - "8081:8080"

    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        ports:
        - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka1:
        image: confluentinc/cp-kafka
        hostname: kafka1
        depends_on:
        - zookeeper
        ports:
        - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    kafka2:
        image: confluentinc/cp-kafka
        hostname: kafka2
        depends_on:
        - zookeeper
        ports:
        - "9093:9092"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    kafka3:
        image: confluentinc/cp-kafka
        hostname: kafka3
        depends_on:
        - zookeeper
        ports:
        - "9094:9092"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    spark-master:
        image: docker.io/bitnami/spark:3.5
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_USER=spark
        ports:
            - "9090:8080"
            - "7077:7077"
        volumes:
            - ./dags:/opt/bitnami/spark/jobs


    spark-worker-1:
        <<: *spark-common
    spark-worker-2:
        <<: *spark-common